<?php
// This file generated by Propel 1.7.0-dev convert-conf target
return array (
  'hhc\\DB\\Hero' => 'hhc/Hero.php',
  'hhc\\DB\\HeroPeer' => 'hhc/HeroPeer.php',
  'hhc\\DB\\HeroQuery' => 'hhc/HeroQuery.php',
  'hhc\\DB\\User' => 'hhc/User.php',
  'hhc\\DB\\UserPeer' => 'hhc/UserPeer.php',
  'hhc\\DB\\UserQuery' => 'hhc/UserQuery.php',
  'hhc\\DB\\map\\HeroTableMap' => 'hhc/map/HeroTableMap.php',
  'hhc\\DB\\map\\UserTableMap' => 'hhc/map/UserTableMap.php',
  'hhc\\DB\\om\\BaseHero' => 'hhc/om/BaseHero.php',
  'hhc\\DB\\om\\BaseHeroPeer' => 'hhc/om/BaseHeroPeer.php',
  'hhc\\DB\\om\\BaseHeroQuery' => 'hhc/om/BaseHeroQuery.php',
  'hhc\\DB\\om\\BaseUser' => 'hhc/om/BaseUser.php',
  'hhc\\DB\\om\\BaseUserPeer' => 'hhc/om/BaseUserPeer.php',
  'hhc\\DB\\om\\BaseUserQuery' => 'hhc/om/BaseUserQuery.php',
);
